### ISSUE TITLE
[Feature request]: /execute compatibility for /vl

### ISSUE THREAD

**Issue by TheVisionaryOne** [FamroFexl/ViewLock#5]
### Suggestion

Love the View Lock mod, and I could see it having a lot of applications for modpacks and mapmaking! It's an incredible utility for restricting the players camera movement, and it's a much more efficient strategy than spamming "/tp @s facing" via a datapack or something.

However, I was disappointed to discover that the /vl command cannot be run from /execute. It also prevents any functions that simply contain the command "vl" from being loaded, completely bricking them if the command is even included in the .mcfunction file. I assume this is likely because /vl is a client-side command, not a server-side command, which is a shame.

I would love to be able to utilize View Lock as a serverside utility, and I'd imagine I won't be the only one who feels this way. If it's not too much trouble, /vl compatibility with the /execute command would be amazing!

**Comment by FamroFexl** [comment]
Yes, viewlock is client-side only, and it required quite a bit of fiddling to get it to accept client-side commands with server-side arguments (such as coordinates). A whole separate server-side command would need to exist in order for this to be possible.

While playing maps, players don't normally use mods in conjunction, so I fail to see the application, and most servers use bukkit/paper instead of fabric. 

I'm not sure why you would specifically need compatibility with /execute however, as the /vl command would already contain a target entity and angle adjustments.

I'll see how much of a rework it will require, and get back to you.

**Comment by FamroFexl** [comment]
I'm not sure why you would specifically need compatibility with /execute however, as the command would already contain a target entity and angle adjustments.
